name: origemdomal
description: A new Flutter project.

# Prevenir publicação acidental no pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# A seção de dependências lista os pacotes que seu app precisa.
dependencies:
  flutter:
    sdk: flutter

  # Suas dependências de pacotes
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.5
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# A seção a seguir é para configurações específicas do Flutter.
flutter:
  uses-material-design: true

  # A declaração de assets (para incluir a pasta 'images')
  assets:
    - images/